### ISSUE TITLE
Import data 

### ISSUE THREAD

**Issue by toJenss** [SAP-samples/product-footprint-management#8]
Hi, 
I am trying to import the 'sample'data for a while now, however, I did not succeed yet to have the data in the PFM solution. I followed every step described in the guide and every step is successful as described: I get the access token, replicationid etc, with as last step the verification that the last response is 204 NO CONTENT. However, I see in the header data of the 'Get Access Token' that the x-frame-options = DENY and x-xss-protection = 1;mode=block. Could it be that this parameters are causing the fact I can not successfully import the data into the PFM solution? Or is there another configuration step I am missing?  I was hoping that someone knows what the issue might be. Thanks in advance. 

Kind regards, 
Jens

edit: I don't see the ReplicationId in the response body at the end of the replication run, but this is also not visible in the screenshot of the guide; 

"3. Verify that the response status is _201 CREATED_ and the response body contains a **replicationRunId**."

**Comment by vinayakgole78** [comment]
Hello Jens,
Could you please let me know how you were able to upload the data? I am still not able to upload after following the steps mentioned.
Thanks
Vinayak

**Comment by toJenss** [comment]
Hi Vinayak,

In postman I used oauth2.0 where I had to put /oauth/token at the end of
the access token url. After this it worked. However, the data will be
imported in the classic calculator. Which will be out of service in a few
months. So I don’t think this test data / manual is really usefull anymore.

Kind regards,
Jens
